### ISSUE TITLE
[BUG] 1.8.1 DoH 服务器运行一段时间后出错退出

### ISSUE THREAD

**Issue by rampageX** [IrineSistiana/mosdns#121]
**出现了什么问题**

1.8.1 DoH 服务器运行一段时间后出错

```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x66e112]

goroutine 98 [running]:
crypto/tls.(*Conn).readClientHello(0xc000088700, 0xd0, 0xd1e4a0, 0x64e796)
	crypto/tls/handshake_server.go:140 +0x92
crypto/tls.(*Conn).serverHandshake(0xc000088700, 0x7ff3a0a982c0, 0xdb7d7c)
	crypto/tls/handshake_server.go:41 +0x45
crypto/tls.(*Conn).Handshake(0xc000088700, 0x0, 0x0)
	crypto/tls/conn.go:1391 +0xc9
crypto/tls.(*Conn).Read(0xc000088700, 0xc0022a4e86, 0x2, 0x2, 0x0, 0x0, 0x0)
	crypto/tls/conn.go:1263 +0x53
io.ReadAtLeast(0x7ff3a04ad520, 0xc000088700, 0xc0022a4e86, 0x2, 0x2, 0x2, 0xc00001e000, 0xcc3620, 0xd93100)
	io/io.go:328 +0x87
io.ReadFull(...)
	io/io.go:347
github.com/IrineSistiana/mosdns/dispatcher/pkg/dnsutils.ReadMsgFromTCP(0x7ff3a04ad520, 0xc000088700, 0x0, 0x0, 0x0, 0x0)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/dnsutils/net_io.go:152 +0xd4
github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*Server).serveTCP.func1(0xea6ff8, 0xc000088700, 0xc000192b30, 0xc0000c6fd0, 0xea1f58, 0xc00464f4c0)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/server/tcp.go:92 +0x153
created by github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*Server).serveTCP
	github.com/IrineSistiana/mosdns/dispatcher/pkg/server/tcp.go:86 +0x44b
```

---

mosdns 的版本号(`mosdns -v`)： v1.8.1-0-g5713468

**Comment by IrineSistiana** [comment]
试试1.8.2？

**Comment by rampageX** [comment]
@IrineSistiana 手动狂刷了一阵貌似没问题了~

**Comment by IrineSistiana** [comment]
问题在dot服务器，打错变量了，空指针了。要是dot能用就没问题了。

（直接把服务器暴露在公网，不怕被扫描么？🤔
