### ISSUE TITLE
[BUG]redis: can't marshal *pool.Buffer

### ISSUE THREAD

**Issue by w22gb8** [IrineSistiana/mosdns#286]
最新版本使用redis缓存出现错误：
```
failed to store cache: redis: can't marshal *pool.Buffer (implement encoding.BinaryMarshaler)
```

**Comment by w22gb8** [comment]
好像还有问题：
```
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]: panic: runtime error: invalid memory address or nil pointer dereference
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4ee89c]
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]: goroutine 53 [running]:
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]: github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/pool.(*Buffer).Release(...)
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]:         github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/pool/allocator.go:151
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]: github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/upstream.(*Transport).exchangeNoKeepAlive.func1(0x400022e7e0, {0x9496d0, 0x400051a010}, 0x40005200c0, {0x93d658, 0x40000a8300})
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]:         github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/upstream/transport.go:169 +0x16c
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]: created by github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/upstream.(*Transport).exchangeNoKeepAlive
2月 11 18:14:14 ubuntu-20.04 mosdns[7790]:         github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/upstream/transport.go:163 +0x14c
```
