### ISSUE TITLE
[Bug] 按照wiki中的配置示例，加载v2ray的geoip.dat文件报错

### ISSUE THREAD

**Issue by miniers** [IrineSistiana/mosdns#413]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.1.3-0-g008c5bd

### 操作系统

debian 10

### Bug 描述和复现步骤

按照wiki中的配置示例，加载v2ray的geoip.dat文件报错
<img width="1015" alt="iShot_2022-06-30_22 23 26" src="https://user-images.githubusercontent.com/2039910/176702670-48330266-28a3-49ad-aa76-27099f3bef2f.png">

同样的配置文件，在4.1.2中完全正常
<img width="1005" alt="iShot_2022-06-30_22 22 51" src="https://user-images.githubusercontent.com/2039910/176702759-ac05486d-cab1-46c7-ac89-df8bf5aeaf66.png">

### 使用的配置文件

```yaml
log:
  level: debug
  file: ""

data_providers:
  - tag: geosite
    file: ./geosite.dat
    auto_reload: true
  - tag: geoip
    file: ./geoip.dat
    auto_reload: true
  - tag: proxy
    file: ./proxy.txt
    auto_reload: true
  - tag: block
    file: ./block.txt
    auto_reload: true
  - tag: direct
    file: ./direct.txt
    auto_reload: true
  - tag: hosts
    file: ./hosts.txt
    auto_reload: true

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 5120

  # 转发至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: 'https://223.5.5.5/dns-query'
          trusted: true
          dial_addr: '223.5.5.5:443'
        - addr: 'https://doh.pub/dns-query'
          trusted: true
          dial_addr: '120.53.80.136:443'
  # 转发至代理服务器的插件
  - tag: forward_proxy_dns 
    type: fast_forward
    args:
      upstream:
        - addr: 198.18.0.2

  # 转发至远程服务器的插件
  - tag: forward_remote               # 转发至远程服务器的插件
    type: sequence
    args:
      exec:
        - primary:            # 主要执行序列。执行序列说明见 `sequence` 插件的 `exec` 参数。
            - forward_proxy_dns
          secondary:          # 次要执行序列。同上。
            - forward_local
          # stat_length: 30     # 统计长度。默认 10。
          # threshold: 10        # 触发阈值。不可大于统计长度。默认 5。
          fast_fallback: 200    # 快速 fallback 触发阈值。单位: 毫秒。默认: 0，禁用快速 fallback。可省略。
          always_standby: true # 快速 fallback secondary 始终待命。可省略。

  - tag: 'hosts'
    type: 'hosts'
    args:
      hosts:
        - 'provider:hosts'

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:cn'
        - 'provider:direct'

  - tag: domain_is_force_proxy         # 强制远端解析
    type: query_matcher
    args:
      domain:
        - 'provider:proxy'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:category-ads-all'
        - 'provider:block'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - hosts  # hosts
        - _misc_optm  # hosts
        # 缓存
        - cache

        # 屏蔽广告域名
        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return

        # 已知的本地域名用本地服务器解析
        - if: query_is_local_domain
          exec:
            - forward_local
            - _return

        # 已知的非本地域名用远程服务器解析
        - if: "query_is_non_local_domain || domain_is_force_proxy"
          exec:
            - _prefer_ipv4
            - forward_remote
            - _return

          # 剩下的未知域名用 IP 分流。
          # 这里借助了 `fallback` 工作机制。分流原理请参考 `fallback`
          # 的工作流程。
          # primary 从本地服务器获取应答，丢弃非本地 IP 的结果。
        - primary:
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
            # - if: "[_response_valid_answer]"
              exec:
                - _drop_response
          # secondary 从远程服务器获取应答。
          secondary:
            - _prefer_ipv4
            - forward_remote
          # 这里建议设置成 local 服务器正常延时的 2~5 倍。
          # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
          # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
          # 这时用就采用 remote 的应答。单位: 毫秒。
          fast_fallback: 200

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: 0.0.0.0:53
      - protocol: tcp
        addr: 0.0.0.0:53
# API 入口设置     
api:
  http: "0.0.0.0:8080"
```

### mosdns 的 log 记录

```txt
root@docker-breakwall:~/mosdns# ./mosdns_4.1.3 version
v4.1.3-0-g008c5bd
root@docker-breakwall:~/mosdns# ./mosdns_4.1.3 start
2022-06-30T14:23:04.902Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "cache", "type": "cache"}
2022-06-30T14:23:04.902Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "forward_local", "type": "fast_forward"}
2022-06-30T14:23:04.902Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "forward_proxy_dns", "type": "fast_forward"}
2022-06-30T14:23:04.902Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "forward_remote", "type": "sequence"}
2022-06-30T14:23:04.902Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "hosts", "type": "hosts"}
2022-06-30T14:23:04.902Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "query_is_local_domain", "type": "query_matcher"}
2022-06-30T14:23:04.997Z	info	query_matcher/query_matcher.go:116	domain matcher loaded	{"length": 66882}
2022-06-30T14:23:04.997Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "domain_is_force_proxy", "type": "query_matcher"}
2022-06-30T14:23:04.997Z	info	query_matcher/query_matcher.go:116	domain matcher loaded	{"length": 0}
2022-06-30T14:23:04.997Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "query_is_non_local_domain", "type": "query_matcher"}
2022-06-30T14:23:05.070Z	info	query_matcher/query_matcher.go:116	domain matcher loaded	{"length": 31907}
2022-06-30T14:23:05.070Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "query_is_ad_domain", "type": "query_matcher"}
2022-06-30T14:23:05.166Z	info	query_matcher/query_matcher.go:116	domain matcher loaded	{"length": 53109}
2022-06-30T14:23:05.166Z	info	coremain/mosdns.go:123	loading plugin	{"tag": "response_has_local_ip", "type": "response_matcher"}
panic: invalid prefix in list

goroutine 1 [running]:
github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist.(*List).Sort(0xc00071b820)
	github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist/list.go:78 +0x545
github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist.NewV2rayIPDat(0xc0013a0000, {0xc0000b25df, 0x2})
	github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist/load_helper.go:216 +0x22f
github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist.ParseV2rayIPDat({0xc004046000?, 0xc00009e060?, 0x0?}, {0xc0000b25df, 0x2})
	github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist/load_helper.go:193 +0x48
github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist.BatchLoadProvider.func1({0xc004046000?, 0x8d39bc?, 0xc0000d7398?})
	github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist/load_helper.go:104 +0x26
github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist.(*DynamicMatcher).Update(0xc0000aca98, {0xc004046000?, 0xc000055c00?, 0x1?})
	github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist/load_helper.go:72 +0x2f
github.com/IrineSistiana/mosdns/v4/pkg/data_provider.(*DataProvider).LoadAndAddListener(0xc00007c0a0, {0xef1fe0?, 0xc0000aca98})
	github.com/IrineSistiana/mosdns/v4/pkg/data_provider/data_provider.go:125 +0x124
github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist.BatchLoadProvider({0xc0036fe4b0, 0x1, 0x8?}, 0x2?)
	github.com/IrineSistiana/mosdns/v4/pkg/matcher/netlist/load_helper.go:117 +0x3b1
github.com/IrineSistiana/mosdns/v4/plugin/matcher/response_matcher.newResponseMatcher(0xc0037040c0, 0xc003708050)
	github.com/IrineSistiana/mosdns/v4/plugin/matcher/response_matcher/response_matcher.go:90 +0x379
github.com/IrineSistiana/mosdns/v4/plugin/matcher/response_matcher.Init(0xc0000b25b8?, {0xc65e00?, 0xc003708050?})
	github.com/IrineSistiana/mosdns/v4/plugin/matcher/response_matcher/response_matcher.go:65 +0x32
github.com/IrineSistiana/mosdns/v4/coremain.NewPlugin(0xc0000d7948, 0xdc8911?, 0xc0000d7a28?)
	github.com/IrineSistiana/mosdns/v4/coremain/register.go:103 +0x126
github.com/IrineSistiana/mosdns/v4/coremain.RunMosdns(0xc0000ea790)
	github.com/IrineSistiana/mosdns/v4/coremain/mosdns.go:124 +0xcd3
github.com/IrineSistiana/mosdns/v4/coremain.StartServer(0xc000140cc0)
	github.com/IrineSistiana/mosdns/v4/coremain/run.go:132 +0x445
github.com/IrineSistiana/mosdns/v4/coremain.init.0.func1(0xc00014ef00?, {0xdc289f?, 0x0?, 0x0?})
	github.com/IrineSistiana/mosdns/v4/coremain/run.go:60 +0xca
github.com/spf13/cobra.(*Command).execute(0xc00014ef00, {0x1499bb0, 0x0, 0x0})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x145ce40)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/IrineSistiana/mosdns/v4/coremain.Run(...)
	github.com/IrineSistiana/mosdns/v4/coremain/run.go:94
main.main()
	github.com/IrineSistiana/mosdns/v4/main.go:47 +0x25
```

**Comment by zhaibin18** [comment]
同样的问题
