### ISSUE TITLE
[BUG] 程序强制退出 有 堆栈信息和配置打包提供

### ISSUE THREAD

**Issue by kuyagic** [IrineSistiana/mosdns#48]
服务突然就退出了

描述一下问题的表现。可以直接附上截图或log。建议配置`logger`插件使用`debug`级别获取更详细的调试log。
用 systemctl 看到的日志如下
```
Jan 25 23:00:42 zmbox systemd[1]: Stopped Mos DNS Server.
Jan 25 23:00:42 zmbox systemd[1]: Started Mos DNS Server.
Jan 25 23:00:42 zmbox mosdns[24108]: 2021-01-25T23:00:42.969+0800        info        mosdns/main.go:136        mosdns ver: v1.2.0-0-ga0c57e1
Jan 25 23:00:42 zmbox mosdns[24108]: 2021-01-25T23:00:42.969+0800        info        mosdns/main.go:137        arch: amd64, os: linux, go: go1.15.7
Jan 25 23:00:42 zmbox mosdns[24108]: 2021-01-25T23:00:42.969+0800        info        mosdns/main.go:157        current working directory: /opt/config/mosdns
Jan 25 23:00:42 zmbox mosdns[24108]: 2021-01-25T23:00:42.969+0800        info        coremain/run.go:61        loading config        {"file": "/opt/config/mosdns/entry.yaml"}
Jan 25 23:00:44 zmbox mosdns[24108]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 25 23:00:44 zmbox mosdns[24108]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x96f173]
Jan 25 23:00:44 zmbox mosdns[24108]: goroutine 13 [running]:
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward.(*fastUpstream).exchangeTCP(0xc002835920, 0xc00030f710, 0x0, 0x0, 0x0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/upstream.go:256 +0x53
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward.(*fastUpstream).exchangeUDPWithTCPFallback(0xc002835920, 0xc00030f710, 0x2, 0x2, 0xc00507de50)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/upstream.go:318 +0x87
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward.(*fastUpstream).Exchange(0xc002835920, 0xc00030f710, 0xc006254000, 0x10, 0x682656790130c7b0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/upstream.go:213 +0xd2
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/utils.ExchangeParallel(0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0xc0001fb550, 0x1, 0x1, 0xc0028357a0, 0xc004f9ec00, 0xc0026f2880, 0x8)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/utils/utils.go:266 +0xf67
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward.(*fastForward).exchange(0xc005e77cc0, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0x203000, 0x93803d, 0xc0002e24b0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/fast_forward.go:150 +0x106
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward.(*fastForward).exec(0xc005e77cc0, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0x80, 0x80)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/fast_forward.go:136 +0x4d
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward.(*fastForward).Exec(0xc005e77cc0, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0x7fcf47765560, 0xc000162280)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/fast_forward.go:132 +0x49
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/handler.(*PluginWrapper).ExecES(0xc0028359e0, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0x2, 0x2, 0x0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/handler/plugin_wrapper.go:113 +0xba
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/utils.executablePluginTag.ExecCmd(0xc004f98280, 0x1b, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0xc002835f20, 0x0, 0x0, 0xc005084200, 0x0, ...)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:48 +0x2e5
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/utils.(*ExecutableCmdSequence).ExecCmd(0xc00009cc20, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0xc002835f20, 0xc005084a50, 0xc005084aa0, 0xc005084af0, 0xc005084b40, 0xc005084b90)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:602 +0x9d
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/utils.WalkExecutableCmd(0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0xc002835f20, 0xe1d9c0, 0xc00009cc20, 0x203001, 0x3b0000c0050859a0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:621 +0x82
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/sequence.(*sequenceRouter).Exec(0xc0002f2190, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0xc00019e7e0, 0xc0050959a0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/sequence/sequence.go:64 +0x65
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/handler.(*PluginWrapper).ExecES(0xc004f9e120, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0x0, 0x0, 0x0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/handler/plugin_wrapper.go:113 +0xba
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/utils.(*DefaultServerHandler).execEntry(0xc0002f2ba0, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0x2, 0x2)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/utils/server_handler.go:112+0x90
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/utils.(*DefaultServerHandler).ServeDNS(0xc0002f2ba0, 0xe306c0, 0xc004f9ec00, 0xc0026f2880, 0xe1d980, 0xc0002e3bf0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/utils/server_handler.go:82 +0x2f1
Jan 25 23:00:44 zmbox mosdns[24108]: github.com/IrineSistiana/mosdns/dispatcher/plugin/server.(*ServerGroup).startUDP.func1.1(0xe30640, 0xc0000a42c0, 0xc0049d5e00, 0xc0026f2880, 0xc0002e3bf0)
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/server/udp.go:91 +0xb3
Jan 25 23:00:44 zmbox mosdns[24108]: created by github.com/IrineSistiana/mosdns/dispatcher/plugin/server.(*ServerGroup).startUDP.func1
Jan 25 23:00:44 zmbox mosdns[24108]:         github.com/IrineSistiana/mosdns/dispatcher/plugin/server/udp.go:88 +0x4a6
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：
版本号 `v1.2.0-0-ga0c57e1`
使用的启动参数或启动方式：

操作系统和平台：

进行了什么操作导致了问题的出现：

使用的配置文件：

```yaml

````
如果有需要提供 配置 我可以发整个打包给你
因为我这里分了很多配置.想着一次打包都发了

**Comment by IrineSistiana** [comment]
感谢反馈, 已解决.

**Comment by IrineSistiana** [comment]
问题解决了但我还想改一些东西, 这个问题是udp协议的,你可以先暂时换成tcp或其他协议.

题外话,能发给我你的配置文件吗,我好奇为什么udp模式会触发tcp回滚.谢谢.

**Comment by kuyagic** [comment]
@IrineSistiana 能否提供个邮箱地址 我把配置不mask给你
或者你提供下你的 PGP key 我打包加密给你也行
我配置的上游 应该都是 udp 的 没有配置 tcp 和 doh dot 等

**Comment by IrineSistiana** [comment]
不是很方便留邮箱。

> 我配置的上游 应该都是 udp 的 没有配置 tcp 和 doh dot 等

但是 server 有 tcp 对吧？

**Comment by kuyagic** [comment]
> 不是很方便留邮箱。
> 
> > 我配置的上游 应该都是 udp 的 没有配置 tcp 和 doh dot 等
> 
> 但是 server 有 tcp 对吧？

server 是 本地 udp 的
上游 都是 udp 非标准端口的dns

**Comment by kuyagic** [comment]
> 不是很方便留邮箱。
可以提供下 pgp 的key 也可以 我加密后发这里给你

**Comment by IrineSistiana** [comment]
能告诉我上游是哪些吗？

**Comment by kuyagic** [comment]
这是我 forward.yaml
```
plugin:
  - tag: 'forward_to_chn_dns'
    type: 'forward'
    args:
      bootstrap: []
      deduplicate: false
      insecure_skip_verify: false
      timeout: 10
      upstream:
        - addr: '119.29.29.29'
        - addr: '180.76.76.76'
        - addr: '1.2.4.8'
        - addr: '114.114.114.114'

  - tag: 'forward_to_oversea_dns'
    type: 'forward'
    args:
      bootstrap: []
      deduplicate: false
      insecure_skip_verify: false
      timeout: 10
      upstream:
        - addr: '208.67.222.222:5353'
        - addr: 'tls://9.9.9.11'

        
  - tag: 'fast_forward_to_oversea_dns'
    type: 'fast_forward'
    args:
      upstream:
         # USTC Linux User Group
#        - protocol: 'udp'
#          addr: '202.141.162.123:5353'
        - protocol: 'udp'
          addr: '9.9.9.9:9953' # Quad-9
        
  - tag: 'fast_forward_to_clean_dns'
    type: 'fast_forward'
    args:
      upstream:
        # USTC Linux User Group
        - protocol: 'udp'
          addr: '202.141.178.13:5353'

```

本来是没有注释 `202.141.162.123` 这个上游的 但是报错了 后来注释了这个上游还是报错

下面是入口的sequence
```
#主流程 带hosts 和 自定义匹配
  - tag: 'main_server_seq'
    type: 'sequence'
    args:
      exec:
        - 'check_hosts'
        - 'forward_to_chn_dns'
        - if:
            - 'match_chn_response'
            - 'match_cloudflare_ip_response'
          exec:
            - 'ad_check_seq'
            - '_end'
        - 'add_ecs_info'
        - 'fast_forward_to_oversea_dns'
        - 'ad_check_seq'
        - '_default_cache'
        - '_end'
```

**Comment by IrineSistiana** [comment]
感谢提供配置。

> 本来是没有注释 202.141.162.123 这个上游的 但是报错了 后来注释了这个上游还是报错

其实不是上游的问题。。

bug 是 udp 协议的 fallback。如果收到了被截断的 udp 回应(udp 有最大传输大小)，`fast_forward` 会尝试用同地址的 tcp 重试(fallback)。然后fallback有bug就崩了。

有被截断的 udp 回应说明要用 tcp了。

下个版本会修正这个问题，然后改善这个fallback机制。你可以先用 `forawrd`的udp。

**Comment by kuyagic** [comment]
好的 感谢。

**Comment by IrineSistiana** [comment]
哦对了，刚刚想到的一个问题。

即使fallback成功了，因为你的下游是 udp，也未必能成功传回去。

**Comment by kuyagic** [comment]
至少处理到 不要程序崩溃 有这类情况 推荐 在日志 Warn 级别记录下 就差不多了吧 估计无解?

目前 `mosdns` 被我用来当 局域网的 dns 了 就是单纯转发 非标准udp端口的查询和提供hosts
还有一些特定的 包括不限于广告 的只能在 mosdns 里自由处理的逻辑

如果能提供 反向ptr 指定功能就更好了（
