### ISSUE TITLE
[BUG] 1.3版本崩溃 fatal error: concurrent map writes

### ISSUE THREAD

**Issue by vrichv** [IrineSistiana/mosdns#56]
**出现了什么问题**
同配置1.2升级到1.3以后，使用10来分钟之后，会出现崩溃，进程状态变成Z。
重复出现3次，回退到1.2之后一切正常。

```
# ps |grep mos
 2402 admin        0 Z    [mosdns]
 2471 admin     1716 S    grep mos
 # killall mosdns

 # ./mosdns &
 # 2021-01-29T13:02:30.859Z	info	mosdns/main.go:136	mosdns ver: v1.3.0-0-g6e24aef
2021-01-29T13:02:30.860Z	info	mosdns/main.go:137	arch: mipsle, os: linux, go: go1.15.7
2021-01-29T13:02:30.861Z	info	coremain/run.go:61	loading config	{"file": "config.yaml"}
2021-01-29T13:02:30.873Z	info	coremain/run.go:97	loading plugin	{"tag": "main_server"}
2021-01-29T13:02:30.875Z	info	main_server	server/udp.go:56	udp server started	{"addr": "[::]:53"}
2021-01-29T13:02:30.877Z	info	coremain/run.go:97	loading plugin	{"tag": "main_sequence"}
2021-01-29T13:02:30.879Z	info	coremain/run.go:97	loading plugin	{"tag": "forward_local"}
2021-01-29T13:02:30.881Z	info	coremain/run.go:97	loading plugin	{"tag": "forward_remote"}
2021-01-29T13:02:30.883Z	info	coremain/run.go:97	loading plugin	{"tag": "query_is_local_domain"}
2021-01-29T13:02:31.569Z	info	coremain/run.go:97	loading plugin	{"tag": "query_is_non_local_domain"}
2021-01-29T13:02:31.570Z	info	coremain/run.go:97	loading plugin	{"tag": "query_is_ad_domain"}
2021-01-29T13:02:31.683Z	info	coremain/run.go:97	loading plugin	{"tag": "match_blackip"}
2021-01-29T13:02:31.691Z	info	coremain/run.go:41	all plugins are successfully loaded
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 887 [running]:
runtime.throw(0x92cff8, 0x15)
	runtime/panic.go:1116 +0x60 fp=0x1b064b4 sp=0x1b064a0 pc=0x4fe24
runtime.mapdelete_faststr(0x85f600, 0x10615c0, 0x1b56360, 0x2f)
	runtime/map_faststr.go:377 +0x418 fp=0x1b064e8 sp=0x1b064b4 pc=0x26144
github.com/IrineSistiana/mosdns/dispatcher/utils.(*LRU).mustDel(0x100a320, 0x1b56360, 0x2f, 0x1cbef20)
	github.com/IrineSistiana/mosdns/dispatcher/utils/lru.go:77 +0xf0 fp=0x1b06500 sp=0x1b064e8 pc=0x477f18
github.com/IrineSistiana/mosdns/dispatcher/utils.(*LRU).Del(...)
	github.com/IrineSistiana/mosdns/dispatcher/utils/lru.go:71
github.com/IrineSistiana/mosdns/dispatcher/plugin/cache.(*memCache).get(0x105e630, 0x9feea0, 0x15f6c40, 0x1b56360, 0x2f, 0x0, 0x0, 0x0, 0xaae14125, 0xffffffee, ...)
	github.com/IrineSistiana/mosdns/dispatcher/plugin/cache/mem_cache.go:79 +0x2f8 fp=0x1b06554 sp=0x1b06500 pc=0x558a5c
github.com/IrineSistiana/mosdns/dispatcher/plugin/cache.(*cachePlugin).searchAndReply(0x100a330, 0x9feea0, 0x15f6c40, 0x1af3630, 0x1b56360, 0x2f, 0x40f200)
	github.com/IrineSistiana/mosdns/dispatcher/plugin/cache/plugin.go:124 +0x368 fp=0x1b06844 sp=0x1b06554 pc=0x559a7c
github.com/IrineSistiana/mosdns/dispatcher/plugin/cache.(*cachePlugin).ExecES(0x100a330, 0x9feea0, 0x15f6c40, 0x1af3630, 0x775d0ab4, 0x1af3720, 0x103a240)
	github.com/IrineSistiana/mosdns/dispatcher/plugin/cache/plugin.go:92 +0x54 fp=0x1b0687c sp=0x1b06844 pc=0x5594ac
github.com/IrineSistiana/mosdns/dispatcher/handler.(*PluginWrapper).ExecES(0x105e660, 0x9feea0, 0x15f6c40, 0x1af3630, 0x2, 0x2, 0x2)
	github.com/IrineSistiana/mosdns/dispatcher/handler/plugin_wrapper.go:111 +0x2e0 fp=0x1b068cc sp=0x1b0687c pc=0x40f528
github.com/IrineSistiana/mosdns/dispatcher/utils.executablePluginTag.ExecCmd(0x12901b0, 0xe, 0x9feea0, 0x15f6c40, 0x1af3630, 0x12803f0, 0x1, 0x0, 0x0, 0x0, ...)
	github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:48 +0x264 fp=0x1b06984 sp=0x1b068cc pc=0x47324c
github.com/IrineSistiana/mosdns/dispatcher/utils.(*executablePluginTag).ExecCmd(0x1286f50, 0x9feea0, 0x15f6c40, 0x1af3630, 0x12803f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0x94 fp=0x1b069b4 sp=0x1b06984 pc=0x47e508
github.com/IrineSistiana/mosdns/dispatcher/utils.(*ExecutableCmdSequence).ExecCmd(0x12849a0, 0x9feea0, 0x15f6c40, 0x1af3630, 0x12803f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:602 +0xa0 fp=0x1b069ec sp=0x1b069b4 pc=0x476d24
github.com/IrineSistiana/mosdns/dispatcher/utils.WalkExecutableCmd(0x9feea0, 0x15f6c40, 0x1af3630, 0x12803f0, 0x9f76a0, 0x12849a0, 0x83d1e0, 0x5)
	github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:621 +0x68 fp=0x1b06ab4 sp=0x1b069ec pc=0x476e50
github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/sequence.(*sequenceRouter).Exec(0x1287210, 0x9feea0, 0x15f6c40, 0x1af3630, 0x775d0ab4, 0x1af36d0)
	github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/sequence/sequence.go:64 +0x70 fp=0x1b06ad8 sp=0x1b06ab4 pc=0x68e660
github.com/IrineSistiana/mosdns/dispatcher/handler.(*PluginWrapper).ExecES(0x1280750, 0x9feea0, 0x15f6c40, 0x1af3630, 0x2, 0x2, 0x0)
	github.com/IrineSistiana/mosdns/dispatcher/handler/plugin_wrapper.go:113 +0xa0 fp=0x1b06b28 sp=0x1b06ad8 pc=0x40f2e8
github.com/IrineSistiana/mosdns/dispatcher/utils.executablePluginTag.ExecCmd(0x1290100, 0xd, 0x9feea0, 0x15f6c40, 0x1af3630, 0x1280240, 0x775d9a68, 0x80, 0x80, 0x775d0ab4, ...)
	github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:48 +0x264 fp=0x1b06be0 sp=0x1b06b28 pc=0x47324c
github.com/IrineSistiana/mosdns/dispatcher/utils.(*executablePluginTag).ExecCmd(0x1286eb8, 0x9feea0, 0x15f6c40, 0x1af3630, 0x1280240, 0x102ca00, 0x382bb0, 0x8d7cb043, 0xbffd1ff0, 0x156caff4)
	<autogenerated>:1 +0x94 fp=0x1b06c10 sp=0x1b06be0 pc=0x47e508
github.com/IrineSistiana/mosdns/dispatcher/utils.(*ExecutableCmdSequence).ExecCmd(0x1284940, 0x9feea0, 0x15f6c40, 0x1af3630, 0x1280240, 0x33, 0xe061e0, 0x0, 0x1e798, 0x25c8c)
	github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:602 +0xa0 fp=0x1b06c48 sp=0x1b06c10 pc=0x476d24
github.com/IrineSistiana/mosdns/dispatcher/utils.WalkExecutableCmd(0x9feea0, 0x15f6c40, 0x1af3630, 0x1280240, 0x9f76a0, 0x1284940, 0x6d48c, 0x195c378)
	github.com/IrineSistiana/mosdns/dispatcher/utils/executable_sequence.go:621 +0x68 fp=0x1b06d10 sp=0x1b06c48 pc=0x476e50
github.com/IrineSistiana/mosdns/dispatcher/utils.(*DefaultServerHandler).execEntry(0x1286ec0, 0x9feea0, 0x15f6c40, 0x1af3630, 0x1136900, 0x77590250)
	github.com/IrineSistiana/mosdns/dispatcher/utils/server_handler.go:106 +0x70 fp=0x1b06d34 sp=0x1b06d10 pc=0x47a74c
github.com/IrineSistiana/mosdns/dispatcher/utils.(*DefaultServerHandler).ServeDNS(0x1286ec0, 0x9feea0, 0x15f6c40, 0x1af3630, 0x9f7660, 0x1cbf1c0)
	github.com/IrineSistiana/mosdns/dispatcher/utils/server_handler.go:81 +0x78 fp=0x1b06fac sp=0x1b06d34 pc=0x479c74
github.com/IrineSistiana/mosdns/dispatcher/plugin/server.(*ServerGroup).startUDP.func1.1(0x9fee60, 0x11f51e0, 0x1280330, 0x1af3630, 0x1cbf1c0)
	github.com/IrineSistiana/mosdns/dispatcher/plugin/server/udp.go:91 +0xb8 fp=0x1b06fd4 sp=0x1b06fac pc=0x764d58
runtime.goexit()
	runtime/asm_mipsx.s:651 +0x4 fp=0x1b06fd4 sp=0x1b06fd4 pc=0x9207c
created by github.com/IrineSistiana/mosdns/dispatcher/plugin/server.(*ServerGroup).startUDP.func1
	github.com/IrineSistiana/mosdns/dispatcher/plugin/server/udp.go:88 +0x3c4

```

---

**如何重现**
mosdns 的版本号(`mosdns -v`)：
1.3
操作系统和平台：
路由器Linux  3.4.113 mipsel softfloat
进行了什么操作导致了问题的出现：
正常使用数分钟后出现。

**Comment by IrineSistiana** [comment]
感谢反馈，应该解决了。

**Comment by IrineSistiana** [comment]
不对，还有问题....
