### ISSUE TITLE
[Bug] 无法创建udp服务器

### ISSUE THREAD

**Issue by brainos233** [IrineSistiana/mosdns#715]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

git f6564ca

### 操作系统

OpenWrt 23.05.0-rc3 和 Debian testing

### Bug 描述和复现步骤

在配置文件中设置一个监听任意地址的udp_server，启动mosdns

### 使用的配置文件

```yaml
log:
  level: debug

plugins:
  - tag: main_sequence
    type: sequence
    args:
      - exec: accept

  # 启动 udp 和 tcp 服务器。
  - type: udp_server
    args:
      entry: main_sequence
      listen: 127.0.0.1:1553
```

### mosdns 的 log 记录

```txt
2023-09-19T00:25:06.630+0800    INFO    working directory changed       {"path": "/etc/mosdns"}
2023-09-19T00:25:06.636+0800    INFO    main config loaded      {"file": "/etc/mosdns/config.yaml"}
2023-09-19T00:25:06.640+0800    INFO    loading plugin  {"tag": "main_sequence", "type": "sequence"}
2023-09-19T00:25:06.641+0800    INFO    loading plugin  {"tag": "anonymouse_udp_server_2", "type": "udp_server"}
2023-09-19T00:25:06.642+0800    INFO    all plugins are loaded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x97a170]

goroutine 37 [running]:
github.com/IrineSistiana/mosdns/v5/pkg/server.(*UDPServer).ServeUDP(0x190f430, 0x191aa78)
        /home/brainos/Builds/tmp_mosdns/mosdns/pkg/server/udp.go:76 +0x274
github.com/IrineSistiana/mosdns/v5/plugin/server/udp_server.StartServer.func1()
        /home/brainos/Builds/tmp_mosdns/mosdns/plugin/server/udp_server/udp_server.go:75 +0xa4
created by github.com/IrineSistiana/mosdns/v5/plugin/server/udp_server.StartServer in goroutine 1
        /home/brainos/Builds/tmp_mosdns/mosdns/plugin/server/udp_server/udp_server.go:73 +0x2b0
```

**Comment by brainos233** [comment]
已确认该问题由 https://github.com/IrineSistiana/mosdns/commit/b668a76c1e5a16c3ba914f62441d01740ffc84a7 导致
