### ISSUE TITLE
[BUG]fast_forward的doh/dot在断网后网络恢复后，进程就蹦了

### ISSUE THREAD

**Issue by mkanako** [IrineSistiana/mosdns#84]
版本1.5.2
平台 mac 10.14.5

100%必现如下
1.关闭wifi，dig请求自然失败
2.重连wifi，第一次dig正常返回，第二次dig进程就蹦了

```
2021-02-23T16:18:47.688+0800	warn	fast_forward_local	utils/utils.go:325	upstream failed	{"query": "zhihu.com. 1 1 43201 1", "from": "223.6.6.6:443", "error": "http request failed: Get \"https://dns.alidns.com/dns-query?dns=AAABAAABAAAAAAAABXpoaWh1A2NvbQAAAQAB\": dial tcp 223.6.6.6:443: connect: network is unreachable"}
2021-02-23T16:18:47.688+0800	warn	fast_forward_local	utils/utils.go:325	upstream failed	{"query": "zhihu.com. 1 1 43201 1", "from": "162.14.21.178:443", "error": "http request failed: Get \"https://doh.pub/dns-query?dns=AAABAAABAAAAAAAABXpoaWh1A2NvbQAAAQAB\": dial tcp 162.14.21.178:443: connect: network is unreachable"}
2021-02-23T16:18:47.688+0800	warn	dns_server	server/server_handler.go:88	entry returned an err	{"query": "zhihu.com. 1 1 43201 1", "error": "dns_diversion: fast_forward_local: no response"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1429a3a]

goroutine 76 [running]:
github.com/IrineSistiana/mosdns/dispatcher/pkg/dnsutils.SubtractTTL(0x0, 0xe0000000a, 0x1e73600)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/dnsutils/ttl.go:70 +0x5a
github.com/IrineSistiana/mosdns/dispatcher/pkg/cache.(*RedisCache).Get(0xc00013a388, 0x19f4128, 0xc000311e60, 0xc003a4f860, 0x1b, 0x0, 0x0, 0x0)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/cache/redis_cache.go:59 +0x1c5
github.com/IrineSistiana/mosdns/dispatcher/plugin/cache.(*cachePlugin).ExecES(0xc0001309c0, 0x19f4128, 0xc000311e60, 0xc0001bd2d0, 0xc000112b50, 0xc00011f948, 0x13cab3a)
	github.com/IrineSistiana/mosdns/dispatcher/plugin/cache/cache.go:103 +0x3cd
github.com/IrineSistiana/mosdns/dispatcher/handler.(*PluginWrapper).ExecES(0xc00013c960, 0x19f4128, 0xc000311e60, 0xc0001bd2d0, 0x0, 0x0, 0x151bcba)
	github.com/IrineSistiana/mosdns/dispatcher/handler/plugin_wrapper.go:120 +0x329
github.com/IrineSistiana/mosdns/dispatcher/pkg/executable_seq.RefESExecutablePlugin.ExecES(0xc00012a0e0, 0xb, 0x19f4128, 0xc000311e60, 0xc0001bd2d0, 0x17c5a00, 0x0, 0x0)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/executable_seq/executable_cmd_sequence.go:49 +0x9f
github.com/IrineSistiana/mosdns/dispatcher/pkg/executable_seq.RefESExecutablePlugin.ExecCmd(...)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/executable_seq/executable_cmd_sequence.go:53
github.com/IrineSistiana/mosdns/dispatcher/pkg/executable_seq.(*ExecutableCmdSequence).ExecCmd(0xc00000c090, 0x19f4128, 0xc000311e60, 0xc0001bd2d0, 0xc000072180, 0x120, 0xc000122318, 0xc000403a70)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/executable_seq/executable_cmd_sequence.go:260 +0x97
github.com/IrineSistiana/mosdns/dispatcher/pkg/executable_seq.ExecRoot(0x19f4128, 0xc000311e60, 0xc0001bd2d0, 0xc000072180, 0x19e75a0, 0xc00000c090, 0x0, 0x0)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/executable_seq/utils.go:30 +0x5d
github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*DefaultServerHandler).execEntry(...)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/server/server_handler.go:110
github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*DefaultServerHandler).ServeDNS(0xc00007e1c0, 0x19f4128, 0xc000311e60, 0xc0001bd2d0, 0x19e7920, 0xc003e00600)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/server/server_handler.go:85 +0x1c5
github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*Server).handleQueryTimeout(0xc00031a000, 0x19f40b8, 0xc0000a5400, 0xc0001bd2d0, 0x19e7920, 0xc003e00600)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/server/server.go:158 +0xc2
github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*Server).startUDP.func1(0x19f8ac8, 0xc00000e050, 0x19edde0, 0xc003e005d0, 0xc0000b3170, 0xc00031a000, 0x19f40b8, 0xc0000a5400)
	github.com/IrineSistiana/mosdns/dispatcher/pkg/server/udp.go:84 +0xf4
created by github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*Server).startUDP
	github.com/IrineSistiana/mosdns/dispatcher/pkg/server/udp.go:77 +0x34e
```

**Comment by IrineSistiana** [comment]
👌

**Comment by mkanako** [comment]
原理只是变量名写错，不关断网的事，我还以为以前的bug重现了🤣
