### ISSUE TITLE
[BUG] 最新版本执行后一段时间报错。日志是 IsEdns 开始

### ISSUE THREAD

**Issue by kuyagic** [IrineSistiana/mosdns#86]
**出现了什么问题**

描述一下问题的表现。可以直接附上截图或log。建议配置`logger`插件使用`debug`级别获取更详细的调试log。

```txt
frps:/opt/config/mosdns# mosdns -c entry.yaml -dir .
2021-02-27T15:10:55.036+0800    info    mosdns/main.go:157      current working directory: .
2021-02-27T15:10:55.039+0800    info    mosdns/main.go:174      mosdns ver: v1.6.0-0-ga2ecc06
2021-02-27T15:10:55.039+0800    info    mosdns/main.go:175      arch: amd64, os: linux, go: go1.16
2021-02-27T15:10:55.041+0800    info    coremain/run.go:60      loading config  {"file": "entry.yaml"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x67ffc6]

goroutine 152 [running]:
github.com/miekg/dns.(*Msg).IsEdns0(0x0, 0xc004e645a0)
        github.com/miekg/dns@v1.1.39/defaults.go:152 +0x26
github.com/IrineSistiana/mosdns/dispatcher/pkg/server.getMaxSizeFromQuery(0x0, 0xc00004a7b0)
        github.com/IrineSistiana/mosdns/dispatcher/pkg/server/udp.go:39 +0x2b
github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*Server).startUDP.func1(0xe0c0a8, 0xc00231d680, 0xe012c8, 0xc004e68360, 0x0, 0xc0000ad5f0, 0xe077d8, 0xc004034dc0)
        github.com/IrineSistiana/mosdns/dispatcher/pkg/server/udp.go:81 +0x2f
created by github.com/IrineSistiana/mosdns/dispatcher/pkg/server.(*Server).startUDP
        github.com/IrineSistiana/mosdns/dispatcher/pkg/server/udp.go:77 +0x34e
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：版本号 1.6.0

使用的启动参数或启动方式：

操作系统和平台：
平台是 Linux Alpine
进行了什么操作导致了问题的出现：

使用的配置文件：
ecs 配置如下

```yaml
plugin:
  - tag: 'add_ecs_info'
    type: 'ecs'
    args:
      auto: false
      force_overwrite: true
      mask4: 24
      mask6: 32
      ipv4: '<my-ip>'
````

**Comment by kuyagic** [comment]
server 定义
```
plugin:
  #entry
  - tag: 'main_server'
    type: 'server'
    args:
      entry: 'main_server_seq'
      #entry: 'main_ctx'
      server:
        - protocol: 'udp'
          addr: '192.168.11.11:53'
```

main_server_seq 定义
```
- tag: 'main_server_seq'
    type: 'sequence'
    args:
      exec:
        - 'check_hosts'
        - 'forward_to_chn_dns'
        - if:
            - 'match_chn_response'
            - 'match_cloudflare_ip_response'
          exec:
            - 'ad_check_seq'
            - '_end'
        - 'add_ecs_info'
        - 'fast_forward_to_oversea_dns'
        - 'ad_check_seq'
        - '_default_cache'
        - '_end'
```

**Comment by IrineSistiana** [comment]
👌

**Comment by kuyagic** [comment]
> 👌

我发现我每次升级都会遇到奇怪的bug 所以我现在只能自己编译下了咯?- -
